In [15]:
import random
import numpy as np
X=np.array(([2,9],[1,5],[3,6],[5,4]),dtype=float)
Y=np.array(([92],[86],[89],[90]),dtype=float)
y=Y/100
m,n=np.shape(Y)
print(m)
print(n)
print(X)
print(y)
def sigmoid(x):
    return 1/(1+np.exp(-x))
def derivatives_sigmoid(x):
    return x*(1-x)
epoch=100000
lr=0.1
inputlayer_neurons=2
hiddenlayer_neurons=3
output_neurons=1
wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
bh=np.random.uniform(size=(1,hiddenlayer_neurons))
wout=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
bout=np.random.uniform(size=(1,output_neurons))
print(wh)
print(bh)
print(wout)
print(bout)
for i in range(epoch):
    h_ip=np.dot(X,wh)+bh
    h_act=sigmoid(h_ip)
    o_ip=np.dot(h_act,wout)+bout
    output=sigmoid(o_ip)
    Eo=y-output
    outgrad=derivatives_sigmoid(output)
    d_output=Eo*outgrad
    Eh=d_output.dot(wout.T)
    hiddengrad=derivatives_sigmoid(h_act)
    d_hidden=Eh*hiddengrad
    wout+=h_act.T.dot(d_output)*lr
    wh+=X.T.dot(d_hidden)*lr
print(wh)
print(wout)
print("normalized input:\n"+str(X))
print("actual output:\n" +str(y))
print("Predicated Output:\n",+output)

4
1
[[2. 9.]
 [1. 5.]
 [3. 6.]
 [5. 4.]]
[[0.92]
 [0.86]
 [0.89]
 [0.9 ]]
[[0.84090414 0.93720762 0.11599101]
 [0.39595157 0.7086743  0.44730002]]
[[0.18553853 0.59366944 0.12458351]]
[[0.3653672 ]
 [0.95897465]
 [0.86669124]]
[[0.80913019]]
[[0.74834041 0.92535365 0.15006301]
 [0.04709981 0.64447131 0.16385827]]
[[ 0.57921661]
 [-0.6253999 ]
 [ 1.73040407]]
normalized input:
[[2. 9.]
 [1. 5.]
 [3. 6.]
 [5. 4.]]
actual output:
[[0.92]
 [0.86]
 [0.89]
 [0.9 ]]
Predicated Output:
 [[0.90073483]
 [0.87295996]
 [0.8963004 ]
 [0.89810939]]
